[5주차] 데이터베이스!
java-squid/lets-cs pull request #30
Opened 2021-07-05 14:04 UTC by Hamill210

- B-tree vs B+tree
- Transaction 이란?

2021-07-06 12:57 UTC, 102092 requested changes

2021-07-06 12:57 UTC, 102092 commented on database/btree-vs-b+tree/hamill/README.md
> +B-tree는 노드가 inorder traversal로 정렬되는 자가 균형 이진 탐색 트리(self-balancing tree)로 알려져 있습니다. B-tree에서 노드는 둘 이상의 자식을 가질 수 있습니다. B-tree의 높이는 logMN 입니다. (여기서 M은 트리 순서, N은 노드 수입니다) 그리고 높이는 업데이트 할 때마다 자동으로 조정됩니다. B
> inorder traversal로 정렬되는 자가 균형 이진 탐색 트리(self-balancing tree)

Q1) 위에 적힌 사항에 대해 조금 더 설명해주시면 좋을듯 합니다!

2021-07-06 12:57 UTC, 102092 commented on database/btree-vs-b+tree/hamill/README.md
> +|7. |중복 검색 키가 없습니다.|중복 검색 키가 있을 수 있습니다.|
😮 한눈에 볼 수 있고 좋네요!

2021-07-06 12:57 UTC, 102092 commented on database/transaction-basic/hamill/README.md
> +2. Rollback 시에는 해당 트랜잭션을 재시작하거나 폐기한다.
Q2) 단순 조회에 해당하는 트랜잭션 일 경우, 해당 트랜잭션 진행 중에 문제가 생겨 실패한 경우에.. 이 트랜잭션은 rollback 을 실행할까요?

2021-07-12 12:05 UTC, jypthemiracle commented on database/btree-vs-b+tree/hamill/README.md
> +B-tree는 노드가 inorder traversal로 정렬되는 자가 균형 이진 탐색 트리(self-balancing tree)로 알려져 있습니다. B-tree에서 노드는 둘 이상의 자식을 가질 수 있습니다. B-tree의 높이는 logMN 입니다. (여기서 M은 트리 순서, N은 노드 수입니다) 그리고 높이는 업데이트 할 때마다 자동으로 조정됩니다. B
inorder traversal도 상당히 재미있는 주제인데요. 순회에 대해서 조금 더 설명하면 재미있을 것 같아요.

2021-07-12 12:11 UTC, jypthemiracle commented on database/btree-vs-b+tree/hamill/README.md
> +B+tree는 트리의 리프 노드에만 데이터 포인터를 저장하여 인덱싱에 사용되는 B-tree의 단점을 제거합니다. 따라서 B+tree의 리프 노드 구조는 B-tree의 내부 노드 구조와 상당히 다릅니다. 데이터 포인터는 리프 노드에만 존재하기 때문에 리프 노드는 액세스하기 위해 디스크 파일 블록에 대한 해당 데이터 포인터와 함께 모든 키값을 반드시 저장해야
```multilevel``` 인덱스라는 표현이 잘 이해가 안되네요. 혹시 추가로 설명해주실 수 있으실까요?

2021-07-12 12:16 UTC, jypthemiracle commented on database/transaction-basic/hamill/README.md
> +1. 트랜잭션은 데이터베이스 시스템에서 병행 제어 및 회복 작업 시 처리되는 작업의 논리적 단위이다.
DB에서 병행 제어란 무엇일까요?

2021-07-12 12:19 UTC, jypthemiracle commented on database/transaction-basic/hamill/README.md
> +1. Commit 연산은 한 개의 논리적 단위(트랜잭션)에 대한 작업이 성공적으로 끝났고 데이터베이스가 다시 일관된 상태에 있을 때, 이 트랜잭션이 행한 갱신 연산이 완료된 것을 트랜잭션 관리자에게 알려주는 연산이다.
트랜잭션 관리자가 무엇인가요?

2021-07-14 04:43 UTC, Hamill210 commented on database/btree-vs-b+tree/hamill/README.md
> +B-tree는 노드가 inorder traversal로 정렬되는 자가 균형 이진 탐색 트리(self-balancing tree)로 알려져 있습니다. B-tree에서 노드는 둘 이상의 자식을 가질 수 있습니다. B-tree의 높이는 logMN 입니다. (여기서 M은 트리 순서, N은 노드 수입니다) 그리고 높이는 업데이트 할 때마다 자동으로 조정됩니다. B
B-tree를 Inorder trabersal(중위 순회)로 동작할 때 모든 값들을 정렬된 순으로 읽을 수 있다는 의미같습니다. B-tree는 이진탐색트리를 기본으로 한 트리형태이기 때문에 이런 동작이 가능합니다.

**inorder traversal**
트리 순회의 종류로 preorder, inorder, postorder 순회가 있는데, 그 중 inorder 순회는 left -> root -> right 순으로 노드를 순회하는 방법

**자가 균형 이진 탐색 트리**
삽입과 삭제가 일어나는 경우에 자동으로 그 높이(루트에서부터 내려갈 수 있는 최대 레벨)를 작게 유지하는 노드 기반 이진 탐색 트리 

**BST의 중위순회(위키피디아)**
중위 순회는 특히 이진 탐색 트리에서 사용되는데, 이진 탐색 트리의 설정에 따른 기본적인 순서에서 값을 반환해야 하기 때문이다. 왜냐하면, 이진 탐색 트리의 노드 n에서, n의 모든 왼쪽 서브 트리는 n보다 작고, n의 모든 오른쪽 서브 트리는 n보다 크거나 같다. 따라서, 만약 왼쪽 서브 트리를 순서대로 방문하게 된다면, 재귀 호출을 사용하고, n을 방문하고, 오른쪽 서브 트리를 순서대로 방문하여, n을 루트로 하는 모든 서브트리를 순서대로 방문하게 된다. 재귀 호출이 정확히 서브 트리를 순서대로 방문하는지 구조적 귀납법의 수학적 원리를 사용하여 추측할 수 있다. 역순 중위 순회는 값을 내림차순으로 정렬하는 것과 비슷하다.

2021-07-14 10:36 UTC, jypthemiracle commented
위 답변만 다 달아주시면 approve 하겠습니다. 수고 많으셨습니다!

2021-07-14 11:43 UTC, Hamill210 commented on database/transaction-basic/hamill/README.md
> +2. Rollback 시에는 해당 트랜잭션을 재시작하거나 폐기한다.
단순 조회의 경우 굳이 트랜잭션을 걸지 않는다고 하는데, 혹 단순 조회의 경우도 트랜잭션을 걸어 진행 중 실패한다해도 롤백을 실행하진 않을 것 같습니다. 롤백이란 업데이트하다 오류가 나면 다시 원래 상태로 복구해주는 기능이라고 생각이 드는데요. 혹시 제가 틀렸다면 코멘트 부탁드립니다!

2021-07-14 11:47 UTC, Hamill210 commented on database/btree-vs-b+tree/hamill/README.md
> +B+tree는 트리의 리프 노드에만 데이터 포인터를 저장하여 인덱싱에 사용되는 B-tree의 단점을 제거합니다. 따라서 B+tree의 리프 노드 구조는 B-tree의 내부 노드 구조와 상당히 다릅니다. 데이터 포인터는 리프 노드에만 존재하기 때문에 리프 노드는 액세스하기 위해 디스크 파일 블록에 대한 해당 데이터 포인터와 함께 모든 키값을 반드시 저장해야
### multilevel index
![image](https://user-images.githubusercontent.com/38041572/125616783-5b238660-ac1c-4dc1-8f65-ee0f4236c3d0.png)

- 데이터가 커지면 index 크기가 커지길 마련입니다. 그러면서 single level index로는 해결 할 수 없는 경우에 multilevel index를 사용한다고 합니다.
- 원리는 inner index(기존 원래 인덱스)를 작은 색인으로 분할하여 outer index를 작게 만드는 것입니다.
- 이로 인한 단점으로는 I/O가 잦다는 점입니다.
- 실제 데이터베이스 파일과 함께 디스크에 저장됩니다.

https://joosjuliet.github.io/index/

2021-07-14 11:49 UTC, Hamill210 commented on database/transaction-basic/hamill/README.md
> +1. 트랜잭션은 데이터베이스 시스템에서 병행 제어 및 회복 작업 시 처리되는 작업의 논리적 단위이다.
병행제어란 여러 개의 트랜잭션이 실행될 때 트랜잭션들이 데이터베이스의 일관성을 파괴하지 않고 다른 트랜잭션에 영향을 주지 않으면서 트랜잭션을 제어하는 것을 의미합니다. 병행제어의 목적은 데이터베이스의 공유와 시스템 활용도의 최대화, 데이터 베이스의 일관성 유지, 사용자에 대한 응답시간을 최소화하는데 있습니다.

2021-07-14 12:38 UTC, Hamill210 commented on database/transaction-basic/hamill/README.md
> +1. Commit 연산은 한 개의 논리적 단위(트랜잭션)에 대한 작업이 성공적으로 끝났고 데이터베이스가 다시 일관된 상태에 있을 때, 이 트랜잭션이 행한 갱신 연산이 완료된 것을 트랜잭션 관리자에게 알려주는 연산이다.
Transaction Manager는 하나 이상의 리소스에서 트랜잭션 조정을 담당하는 애플리케이션의 일부입니다. Transaction Manager의 책임은 다음과 같습니다. Demarcation-시작, 커밋 및 롤백 메서드를 사용하여 트랜잭션을 시작하고 종료합니다.

https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/6.3/html/transaction_guide/txnmanagers

2021-07-14 13:07 UTC, 102092 commented on database/transaction-basic/hamill/README.md
> +2. Rollback 시에는 해당 트랜잭션을 재시작하거나 폐기한다.
제가 이해하기에는, 우선 트랜잭션이 시작되면 무조건 commit or rollback 의 결과가 있어야 한다고 이해했어요 (해당 트랜잭션이 종료되기 위해선)
그래서 단순 조회 트랜잭션이라도.. 뭔가 잘못되어서 해당 트랜잭션에 문제가 생겼다면
데이터에 아무런 변화가 없다고 해도, 롤백을 통해서 해당 트랜잭션을 종료하지 않을까 생각합니다.

참고
- https://stackoverflow.com/questions/309834/should-i-commit-or-rollback-a-read-transaction

2021-07-14 13:09 UTC, 102092 approved these changes
수고하셨습니다!

2021-07-15 06:48 UTC, Hamill210 commented on database/transaction-basic/hamill/README.md
> +2. Rollback 시에는 해당 트랜잭션을 재시작하거나 폐기한다.
@102092 오오..! 알려주셔서 감사합니다!!

2021-07-18 12:10 UTC, merged