[6주차] 데이터베이스
java-squid/lets-cs pull request #31
Opened 2021-07-06 10:54 UTC by jypthemiracle

## 학습한 내용
* [x] B-Tree에 대한 이해, 이를 바탕으로 B+Tree는 무엇인지 개요 학습
* [x] 트랜잭션에 대한 기본적인 이해
* [x] 인덱스에 대한 기본적인 이해

## 회고
* 간단하게 하루에 30분씩만 투자하면 CS 정복을 할 수 있겠다^^ (아님)

2021-07-06 12:42 UTC, 102092 requested changes
첫주차 수고하셨습니다
질문 사항에 대해 남겨드렸으니, 확인 부탁드립니다.
또한 폴더 구조 한번 확인해주세요!

database/btree-vs-b+tree/B+tree.md (bad..)
database/btree-vs-b+tree/sigirid/README.md (good)

2021-07-06 12:42 UTC, 102092 commented on database/btree-vs-b+tree/B-Tree.md
> +* B-Tree는 자식 노드의 개수가 2개 이상인 트리를 말한다.
👍

2021-07-06 12:42 UTC, 102092 commented on database/btree-vs-b+tree/B-Tree.md
> +* Root 노드를 제외한 모든 노드는 적어도 M/2 개의 데이터를 갖고 있어야 한다. 즉, 4차부터는 2개 이상의 데이터를 갖고 있어야 한다.
Q1) 여기서 M이 나타내는 바는 어떤 것일까요?

2021-07-06 12:42 UTC, 102092 commented on database/index-basic/sigrid/sigrid_index.md
> +```
인덱스가 어떻게 동작할 건지를 잘 이해가되네요!

2021-07-06 12:42 UTC, 102092 commented on database/index-basic/sigrid/sigrid_index.md
> +* 우선 ‘Transaction’ 이라는 키워드를 쉽게 찾을 수 있도록 abc 순으로 정렬하면 좋을 것 같다.
Q2) 인덱스를 만들때 어떤 컬럼을 기준으로 만드는 게 보통..좋을까요? (cardinality)

2021-07-06 12:42 UTC, 102092 commented on database/transaction.md
> +#### Checkpoint recovery
이 부분은 좀 덜 완성되어 있는 걸까요?

2021-07-06 12:42 UTC, 102092 commented on database/transaction.md
> +* 트랜잭션 수행 도중 변경하면 변경 정보를 로그 파일에 저장하고, 트랜잭션이 부분 완료되기 전이라도 모든 변경 내용을 즉시 데이터베이스의 반영하는 기법.
Q3) 이 부분에 대해 잘 이해가 안되네요. 좀 더 설명해주실 수 있을까요?
제가 이해하기론.. 트랜잭션 진행 과정에서, 변경사항들을 로그 파일에 저장해두고 있다가...
어떠한 이유에서 인지 해당 트랜잭션이 정상적으로 종료되지 않았더라도,
변경이 된 사항.. 그러니까 로그 파일에 저장되어 있는 내용들은 데이터베이스에 적용이 되도록 하는 기법을 말하는 걸까요?

2021-07-06 13:38 UTC, jypthemiracle commented on database/btree-vs-b+tree/B-Tree.md
> +* Root 노드를 제외한 모든 노드는 적어도 M/2 개의 데이터를 갖고 있어야 한다. 즉, 4차부터는 2개 이상의 데이터를 갖고 있어야 한다.
@102092 M차 B-Tree인 경우를 의미합니다. (ex. 4차 B-Tree 인 경우, 모든 자식 노드는 2개 이상의 데이터를 갖고 있어야 합니다)

2021-07-06 13:39 UTC, jypthemiracle commented
B-Tree가 왜 유의미하게 효율적인가를 증명해보고 싶은데 이는 나중에 CS 전공하게 되면 해보죠 ㅋ

2021-07-08 17:37 UTC, Hamill210 commented
Q1: B-tree와 B+tree의 차이점은 뭘까요? 왜 이 차이점이 면접에 자주 나올까요? (편하게 답변해주시면 됩니다)

2021-07-08 17:39 UTC, Hamill210 commented
Q2: 병행처리와 병렬처리의 차이점에 대해서 공부해보시면 좋을 것 같아요! 그리고 트랜잭션을 병행처리(Concurrency)할 때의 문제점과 해결 방법을 간략히 적어주세요.

2021-07-14 10:16 UTC, jypthemiracle commented on database/index-basic/sigrid/sigrid_index.md
> +* 우선 ‘Transaction’ 이라는 키워드를 쉽게 찾을 수 있도록 abc 순으로 정렬하면 좋을 것 같다.
가. 인덱스는 테이블 당 3개 정도가 적당하다고 합니다. [Index Tuning Week](https://www.brentozar.com/archive/2018/10/index-tuning-week-how-many-indexes-are-too-many/)
나. 주로 4가지의 기준이 있다고 하네요.
* Cardinality: 중복되지 않고 고유성이 보장되어야 좋은 인덱스라고 합니다. 예를 들어 군번은 높은 cardinality를 갖겠습니다. 이와 달리 계급은 낮은 cardinality를 갖습니다.
* Selectivity: Cardinality와 크게 다르지 않은 개념이라고 생각 드는데요. 선택도는 특정 필드값을 지정했을 때 선택되는 레코드 수를 테이블 전체 레코드 수로 나눈 것입니다. 10개 rows를 가지는 ‘20전비 현재병력’ 테이블에 '군번’, ‘이름’, ‘계급’ 컬럼이 있다고 해봅시다. 이 때 군번은 고유하므로, 군번이 가장 selectivity가 낮다고 할 수 있습니다.
* 활용도: 해당 컬럼이 실제 작업에서 얼마나 활용되는지에 대한 값입니다.WHERE 절에 많이 사용되면 해당되겠습니다.
* 중복도: 같은 컬럼에 대해 두 개 이상의 인덱스가 같은 값을 가지면, 메모리를 불필요하게 차지하므로 좋지 않다고 보겠습니다.

2021-07-14 10:18 UTC, jypthemiracle commented on database/transaction.md
> +#### Checkpoint recovery
## Checkpoint Recovery
### Checkpoint
* 특정한 체크포인트로 설정한 지점을 기점으로, 해당 지점 이전에는 트랜잭션이 성공적으로 수행되어 디스크에 저장되어 있다고 보장할 수 있습니다.
* 실패가 일어날 경우, redo는 check point 시점부터 log를 따라가면서 트랜잭션을 수행합니다. undo는 트랜잭션을 거꾸로 재수행하면서 트랜잭션을 없던 일로 만듭니다.

2021-07-14 10:21 UTC, jypthemiracle commented on database/transaction.md
> +#### Checkpoint recovery
![image](https://user-images.githubusercontent.com/41055141/125605863-8ff54452-4279-44f7-a5c0-bcef1f3ff020.png)
* Transaction T1
checkpoint 이전에 실행이 완료되었으므로 failure 되더라도 이미 disk에 저장이 된 상태이므로 회복을 하지 않습니다.
* Transaction T2
checkpoint 이전에 실행된 내용은 disk에 반영이 되었으므로 check point 이후의 내용을 log를 따라가는 redo를 수행합니다.
* Transaction T3
failure 시점에 실행중이였으므로 check point 시점으로 undo한 후, 트랜잭션을 재실행합니다.
* Transaction T4
checkpoint 이후에 실행됐고 failure 시점 전에 실행이 끝났으므로 redo를 수행합니다.
* Transaction T5
checkpoint 이후에 실행됐고 failure 시점에 실행중이였으므로 시작지점까지 undo한 후, 트랜잭션을 재실행합니다.

그러니까 정리하자면,
* 체크포인트 시점 중간에 (스냅샷 찍는 도중에) 실행되는 트랜잭션은 모두 undo한다.
* 체크포인트 시점 이후에 실행된 트랜잭션은 모두 undo한다.
* undo list에 기록된 트랜잭션이 성공적으로 undo되면 이를 다시 redo한다.

2021-07-14 10:24 UTC, jypthemiracle commented on database/transaction.md
> +* 트랜잭션 수행 도중 변경하면 변경 정보를 로그 파일에 저장하고, 트랜잭션이 부분 완료되기 전이라도 모든 변경 내용을 즉시 데이터베이스의 반영하는 기법.
제가 이해하기로는 트랜잭션 진행 과정에서 변경 사항들을 로그 파일에 저장하고 있다가,
특정한 이유에서 해당 트랜잭션이 정상적으로 완료되지 않았더라도,
변경이 된 사항 까지는 바로 commit이 되니까 무시하고, 오류가 났으면 log 파일을 참조해서 어디부터 다시 undo, redo하면 되는 지 참고해서 작업하는 것으로 알고 있습니다.
즉, 모든 변경사항을 별도의 log에 일일이 다 작성하고 문제가 발생했을 경우 이를 참고해서 recovery하는 작업으로 이해했습니다.

2021-07-14 10:34 UTC, jypthemiracle commented
@Hamill210 
1. B+Tree라는 것이 B-Tree에서 파생된 응용 구조이기 때문에, 두 테마를 같이 엮어서 보는 것 같습니다. 이진트리의 확장판으로서 SQL 엔진에서 B-Tree의 응용판이 광범위하게 사용되다보니 SQL 튜닝을 위해서 해당 테마에 대한 이해도를 요구하는 것 같습니다.
2. 병렬처리(Parallel)은 실제로 core level에서 multi core로 처리되는 것을 의미하구요, 병행처리(Concurrency)는 logical level에서 순차적으로 cpu resource를 나눠서(주로 time-sharing으로 시간에 따라 분배) 사용하도록 함으로서 병렬처리인 것 처럼 사용할 수 있게 하는 것을 의미합니다.
3. 트랜잭션이 병렬처리(parallel)을 할 경우 하나의 데이터를 두 개 이상의 트랜잭션이 차지하면 손실되는 데이터가 있을 수 있고, 데이터의 상호 불일치 현상이 일어나서 작업이 깨질 수 있는 우려가 있구요, 마지막으로 하나의 트랜잭션에 문제가 생겨 rollback을 해야 할 경우 다른 트랜잭션도 rollback을 해야 하는 문제가 발생할 수 있겠습니다. 그래서 트랜잭션을 병행처리(concurrency)하도록 함으로서 시간에 따라 Lock해두고 특정한 트랜잭션만 데이터베이스에 접근하여 데이터를 수정하도록 함으로서 발생할 수 있는 문제를 사전에 방지하는 것입니다.

2021-07-14 12:41 UTC, Hamill210 approved these changes
고생하셨습니다!

2021-07-14 13:12 UTC, 102092 approved these changes
> database/transaction-basic/README.md 

-> database/transaction-basic/sigrid/README.md 
이렇게로만 변경 부탁드릴게요.
첫 회차 수고하셨어요!

2021-07-17 11:50 UTC, merged