[8주차] 데이터베이스!
java-squid/lets-cs pull request #41
Opened 2021-08-03 11:15 UTC by Hamill210

2021-08-03 15:08 UTC, jypthemiracle requested changes
요즘 많이 지쳐보이시는 것 같습니다. 하밀하고 같이 위닝했던 순간을 잊을 수가 없는데요. 언제나 즐겁게 코딩하셨으면 좋겠습니다.
저도 시발 빨리 전역하고 싶은데요. 이 ㅈ같은 강제노역에서 저도 언젠가는 해방되지 않겠습니까? 하밀도 화이팅 하시길 바래요. 저도 살아남고 있으니까요. 항상 응원합니다 :+1:

2021-08-03 15:08 UTC, jypthemiracle commented on database/join-in-sql/hamill/README.md
> +# MySQL Join 은 무엇이고 어떤 것이 있을까?
잉? JOIN을 하셨네요.

2021-08-03 15:08 UTC, jypthemiracle commented on database/mysql-query-plan/README.md
> +행이 어떤 SELECT 구문을 나타내는 지를 알려주는 것으로 구문에 서브 쿼리나 UNION이 없다면 SELECT는 하나밖에 없기 때문에 모든 행에 대해 1이란 값이 부여되지만 이외의 경우에는 원 구문에서 순서에 따라 각 SELECT 구문들에 순차적으로 번호가 부여된다.
왜 1이라는 값을 SELECT에 먼저 부여할까요? 2라는 값, 3이라는 값은 언제 부여될까요? 그 이유는 무엇일까요?

2021-08-03 15:08 UTC, jypthemiracle commented on database/mysql-query-plan/README.md
> +### select_type
본인이 생각했을 때 이 중에서 가장 중요한 개념이다 싶은 것을 꼽아주시고 그 이유를 설명해주세요.

2021-08-03 15:08 UTC, jypthemiracle commented on database/mysql-query-plan/README.md
> +### type
이 중에서도 본인이 가장 중요하게 생각하는 Type 하나를 꼽아주시고 그 이유를 설명해주세요.

2021-08-03 15:08 UTC, jypthemiracle commented on database/mysql-query-plan/README.md
> +### extra
본인이 생각했을 때 extra에서 가장 좋은 방법과 가장 나쁜 방법을 하나씩 꼽아보고 그 이유를 서술해주세요.

2021-08-03 15:08 UTC, jypthemiracle commented on database/normalization/hamill/README.md
> +# 1,2,3차 정규화란 무엇인가?
정규화도 있네요. 7주차 머지가 되었는 지 확인 부탁드립니다. @102092

2021-08-03 15:08 UTC, jypthemiracle commented on database/type-of-keys/hamill/README.md
> +```jsx
jsx ㄷㄷ;;;;;

2021-08-03 15:08 UTC, jypthemiracle commented on database/type-of-keys/hamill/README.md
> +2. 외래키는 참조되는 릴레이션의 기본키와 대응되어 릴레이션 간에 참조관계를 표현하는데 중요한 도구이다.
Homework: Surrogate Key vs Natural Key에 대해 조사하시고 해당 논란이 되는 지점과 본인의 의견에 대해 서술해주세요.

2021-08-03 15:08 UTC, jypthemiracle commented on database/type-of-keys/hamill/README.md
> +```
Homework: 기본키가 최소성을 만족해야 하는 이유를 구체적인 예시를 들어 설명해주세요.

2021-08-04 10:38 UTC, 102092 commented on database/normalization/hamill/README.md
> +# 1,2,3차 정규화란 무엇인가?
아마도 fore push 하는 과정에서 벌어진 일 같습니다.

@Hamill210 혹시 가능하시면, local branch (hamil) 에서 `git rebase main` 한번 해보시겠어요?

2021-08-04 10:39 UTC, 102092 commented on database/normalization/hamill/README.md
> +# 1,2,3차 정규화란 무엇인가?
메인 브랜치에 깃이 꼬인듯 싶군요 ㅠㅠ

2021-08-04 10:59 UTC, 102092 commented on database/mysql-query-plan/README.md
> +- UNCACHEABLE UNION: UNION과 동일하지만 공급되는 모든 값에 대하여 UNION 쿼리를 재처리
👍

2021-08-04 10:59 UTC, 102092 commented on database/mysql-query-plan/README.md
> +원하는 행을 찾기 위해 얼마나 많은 행을 읽어야 할지에 대한 예측값을 의미한ㄸ.
```suggestion
원하는 행을 찾기 위해 얼마나 많은 행을 읽어야 할지에 대한 예측값을 의미한다.
```

2021-08-04 10:59 UTC, 102092 commented on database/mysql-query-plan/README.md
> +- DERIVED: SELECT로 추출된 테이블(FROM 절에서의 서브쿼리 또는 Inline View)
Q1) `Inline View` 는 어떤 건가요?

2021-08-04 10:59 UTC, 102092 commented on database/type-of-keys/hamill/README.md
> +2. 외래키는 참조되는 릴레이션의 기본키와 대응되어 릴레이션 간에 참조관계를 표현하는데 중요한 도구이다.
Q2) 외래키의 경우, 기본키가 아닌 다른 키와 매칭될 수는 없을까요?

2021-08-09 14:02 UTC, Hamill210 commented on database/mysql-query-plan/README.md
> +### select_type
select_type 컬럼은 select문의 유형을 알려주는 컬럼으로써 어떤 종류의 select 문임을 알려주는 것 자체로 중요한 컬럼인 것 같습니다. 이 컬럼값으로 SIMPLE, PRIMARY, DERIVED 등 다양한 select_type 유형을 한 눈에 알아볼 수 있어서 그 자체로 유용하다고 생각합니다. 그래도 가장 중요한 개념이라면 SIMPLE일까요? ㅎㅎ 시그리드 생각은 어떠신가요

http://asuraiv.blogspot.com/2015/08/mysql-query-plan.html
https://dansjkim.github.io/posts/database-execution-plan

2021-08-09 14:13 UTC, Hamill210 commented on database/mysql-query-plan/README.md
> +### type
type 은 MySQL이 어떤 방식으로 테이블이 조인되는지 나타내는 항목으로 이 타입에 들어간 값을 분석해서 어떤 인덱스가 사용되고 있는지 혹은 사용되지 않았는지 알 수 있고, 그 결과 어떤 방향으로 쿼리 튜닝을 해야하는지 insight를 제공합니다. 이 질문도 type 자체가 알려주는 정보가 강력하기 때문에 하나를 고르긴 어렵지만 제가 가장 중요하게 생각하는 type은 all 이고, 그 다음은 Index 입니다. 그 이유는 all과 index는 쿼리문이 풀스캔을 돌면서 느리다는 것을 알려주는 지표인데, 해당 지표를 알아야지만 쿼리 튜닝을 시도해야 할지 하지 말아야할지 알기 때문입니다

http://asuraiv.blogspot.com/2015/08/mysql-query-plan.html
https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=realuv&logNo=10184319823

2021-08-09 14:50 UTC, Hamill210 commented on database/type-of-keys/hamill/README.md
> +2. 외래키는 참조되는 릴레이션의 기본키와 대응되어 릴레이션 간에 참조관계를 표현하는데 중요한 도구이다.
처음 보는 주제인데, 흥미로운 주제네요!

테이블의 기본키를 surrogate key vs natural key 중 어떤 걸로 할지 고민의 과정
surrogate key : business 적인 의미가 없는 단순 row를 구분하기 위해 생성하는 컬럼의 키(id)
```sql
CREATE TABLE stock (
    id INT NOT NULL AUTO_INCREMENT,
    ticker VARCHAR(20) NOT NULL,
    price DECIMAL(35, 4),
    PRIMARY KEY (ID)
);
```
natural key: 실제 domain과 연관된 정보로 row를 구분하는 컬럼을 가진 테이블의 키(ticker)
```sql
CREATE TABLE stock (
    ticker VARCHAR(20) NOT NULL,
    price DECIMAL(35, 4),
    PRIMARY KEY (ticker)
);
```

둘다 각각의 장단점이 있지만 natural key의 경우 미래에 값이 변할 가능성이 있기 때문에 surrogate key를 쓰는게 더 낫다고 한다. 현실에서 볼 수 있는 natural key는 주민번호, ISBN 등이 있는데, 이런 값들도 언제든지 변할 가능성이 있기 때문에 surrogate key를 사용하는 게 합리적이라고 한다. 나도 이 의견에 동의하는 바다.

https://rampart81.github.io/post/surrogate_key_vs_natural_key/

2021-08-10 11:39 UTC, 102092 approved these changes

2021-08-14 09:12 UTC, merged