운영체제 14회
java-squid/lets-cs pull request #73
Opened 2021-11-29 13:00 UTC by 102092

issue : #70 , #71
due date : 2021/12/04

2021-11-29 15:26 UTC, jypthemiracle requested changes
조금 추상적이네요. 가상 메모리도 주제별로 나눠서 다시 스터디해봅시다.
바로 다음 주제부터 deep dive 하면 좋을 것 같은데요, 의견 주세요.

2021-11-29 15:26 UTC, jypthemiracle commented on operating-system/virtual-memory/han/README.md
> +- 테이블 접근하기 전에, 찾는 TLB(Translation Lookaside Buffer) 라는 공간도 있음.
구체적인 과정을 정리해보고 싶은데 머리가 아프네요
이 주제 하나만으로 스터디해도 좋을 것 같아요.

2021-11-29 15:26 UTC, jypthemiracle commented on operating-system/virtual-memory/han/README.md
> +    - 여기서 찾고자하는 논리 주소의 값이 있으면 바로 물리 주소를 반환.
Q1: 논리주소의 물리주소 변환 과정을 간단히 적어주시겠어요?

2021-12-07 10:58 UTC, 102092 commented on operating-system/virtual-memory/han/README.md
> +- 테이블 접근하기 전에, 찾는 TLB(Translation Lookaside Buffer) 라는 공간도 있음.
일주일 2개를 줄이고, 하나만 Deep dive 하는 방식으로 변경해도 좋을듯 하네요

2021-12-07 11:07 UTC, 102092 commented on operating-system/virtual-memory/han/README.md
> +    - 여기서 찾고자하는 논리 주소의 값이 있으면 바로 물리 주소를 반환.
1. 컴파일 시점에 주소 할당이 일어나는 경우
- 논리 주소 = 물리주소 이므로 따로 변환이 일어날 것 같진 않네요.

2. 프로그램이 메모리에 올라갈 때 (로드 시점) 에 주소 할당이 일어나는 경우
- 이럴경우 CPU는 프로그램이 올라간 메모리 주소의  base register 을 고려해서 물리주소로 변환시킬듯 싶네요.

3. 실행 시점에 주소가 할당되는 경우
- 이게 이제 위에서 언급된 사항인듯 싶어요.
- 우선 논리 주소를 통해 TLB로 찾아보고 있으면 반환하고 없으면 MMU를 통해서 물리 주소로 바뀌도록 진행될듯 싶습니다.

> 참고
- https://velog.io/@jiyehyeon/OS-%EC%A3%BC%EC%86%8C-%ED%95%A0%EB%8B%B9-%EB%85%BC%EB%A6%AC%EC%A3%BC%EC%86%8C-%EB%AC%BC%EB%A6%AC%EC%A3%BC%EC%86%8C
- https://baked-corn.tistory.com/15

2021-12-08 11:24 UTC, merged